INSERT INTO phone VALUES (1, 'Xiaomi', 'Poco X3')
INSERT INTO phone VALUES (2,'Samsung', 'A10')
INSERT INTO phone VALUES (3,'Motorola',  'G5')
INSERT INTO phone VALUES (4,'Samsung','J3')
INSERT INTO phone VALUES (5,'Samsung','J4 Plus')
INSERT INTO phone VALUES (6,'Motorola',  'G10')
INSERT INTO phone VALUES (7,'Xiaomi', 'Poco F4')
INSERT INTO phone VALUES (8,'Poco F4 GT', 'Xiaomi')
INSERT INTO phone VALUES (9,'Xiaomi', 'Poco X4')
INSERT INTO phone VALUES (10,'Xiaomi', 'Xiaomi 12')
INSERT INTO phone VALUES (11,'Apple', 'Iphone 13')
INSERT INTO phone VALUES (12,'Samsung', 'S22 Ultra')