INSERT INTO phone (brand, name) VALUES ('Xiaomi', 'Poco X3')
INSERT INTO phone (brand, name) VALUES ('Samsung', 'A10')
INSERT INTO phone (brand, name) VALUES ('Motorola', 'G5')
INSERT INTO phone (brand, name) VALUES ('Samsung','J3')
INSERT INTO phone (brand, name) VALUES ('Samsung','J4 Plus')
INSERT INTO phone (brand, name) VALUES ('Motorola', 'G10')
INSERT INTO phone (brand, name) VALUES ('Xiaomi', 'Poco F4')
INSERT INTO phone (brand, name) VALUES ('Poco F4 GT', 'Xiaomi')
INSERT INTO phone (brand, name) VALUES ('Xiaomi', 'Poco X4')
INSERT INTO phone (brand, name) VALUES ('Xiaomi', 'Xiaomi 12')
INSERT INTO phone (brand, name) VALUES ('Apple', 'Iphone 13')
INSERT INTO phone (brand, name) VALUES ('Samsung', 'S22 Ultra')